BreachAchievements = BreachAchievements || {}
BreachAchievements.AchievementTable = {

	{
		name = "halloween",
		achievements_name = "Halloween 2022",
		desc = "spooky",
		image = "nextoren/gui/achievements/halloween.png",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},
	
	{
		name = "wrongescape",
		achievements_name = "走错路了",
		desc = "作为D级/蛇手通过直升机成功逃脱。",
		image = "rxsend/achievements/ahive33.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "shaky",
		achievements_name = "独一无二",
		desc = "如果你有这个成就，说明是沙基决定的",
		image = "nextoren/achievements/ahive3.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "headshot",
		achievements_name = "正中眉心！",
		desc = "爆头击杀一名玩家",
		image = "rxsend/achievements/ahive51.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "fallkill",
		achievements_name = "卡哇邦嘎！",
		desc = "从高处坠落砸死一名玩家",
		image = "rxsend/achievements/ahive89.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true
	},

	{
		name = "cheemer",
		achievements_name = "人类最好的朋友",
		desc = "与奇美拉一起逃脱",
		image = "chemer_icon/chemer.png",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true
	},

	{
		name = "firsttime",
		achievements_name = "初次见面",
		desc = "加入服务器",
		image = "rxsend/achievements/ahive128.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = false,
	},

	{
		name = "lucky",
		achievements_name = "幸运儿",
		desc = "连续2次成为支援",
		image = "rxsend/achievements/ahive128.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = false,
	},

	{
		name = "scp409",
		achievements_name = "相当凉爽……",
		desc = "被SCP-409变成雕像",
		image = "rxsend/achievements/ahive78.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = false,
	},

	{
		name = "secretword",
		achievements_name = "暗号",
		desc = "",
		image = "rxsend/achievements/ahive52.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "chaosradio",
		achievements_name = "你跟我们一起走。",
		desc = "通过蛇之手传送门逃脱。",
		image = "rxsend/achievements/ahive105.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "car",
		achievements_name = "出发！",
		desc = "借助车辆逃脱。",
		image = "rxsend/achievements/ahive115.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "carportal",
		achievements_name = "昂贵设备的损失",
		desc = "驾驶车辆穿过蛇手传送门逃脱……",
		image = "rxsend/achievements/ahive115.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 0,
		textnotify = true,
	},

	{
		name = "comitee",
		achievements_name = "人道委员会",
		desc = "使用伦理监察员的能力5次",
		image = "rxsend/achievements/ahive101.jpg",
		secret = false,
		countable = true,
		countnum = 5,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "scp005",
		achievements_name = "魔法钥匙",
		desc = "使用SCP-005开门",
		image = "rxsend/achievements/ahive16.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "scarlet",
		achievements_name = "猩红之王的孩子",
		desc = "召唤猩红之王",
		image = "rxsend/achievements/ahive121.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},


	{
		name = "bigboom",
		achievements_name = "大爆炸理论",
		desc = "激活核弹并引爆",
		image = "nextoren/achievements/ahive36.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "monorail",
		achievements_name = "带电轨道",
		desc = "乘坐单轨车逃脱",
		image = "nextoren/achievements/ahive54.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "escape",
		achievements_name = "奇迹设施",
		desc = "逃离设施",
		image = "nextoren/achievements/ahive125.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "escapehand",
		achievements_name = "援助之手",
		desc = "借助蛇之手逃脱",
		image = "nextoren/achievements/ahive134.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "apcescape",
		achievements_name = "重型骑兵",
		desc = "乘坐装甲车逃脱",
		image = "nextoren/achievements/ahive118.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "scp0492",
		achievements_name = "我痊愈了",
		desc = "成为SCP-049的受害者",
		image = "nextoren/achievements/ahive138.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "beglec",
		achievements_name = "逃犯",
		desc = "从小门逃脱",
		image = "nextoren/achievements/ahive104.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "fbiescape",
		achievements_name = "不可能完成的任务",
		desc = "带着被黑入的电脑逃脱",
		image = "nextoren/achievements/ahive45.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = true,
	},

	{
		name = "tnt",
		achievements_name = "曼哈顿计划",
		desc = "在咖啡机里使用TNT",
		image = "nextoren/achievements/ahive56.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "gauss",
		achievements_name = "芬里尔",
		desc = "获得高斯炮",
		image = "nextoren/achievements/ahive91.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "secrettoy",
		achievements_name = "有本事就找到我",
		desc = "找到秘密玩具",
		image = "nextoren/achievements/ahive3.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "scp049",
		achievements_name = "瘟疫时期的盛宴",
		desc = "用SCP-049制造5个僵尸",
		image = "nextoren/achievements/ahive70.jpg",
		secret = false,
		countable = true,
		countnum = 5,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "usa",
		achievements_name = "民主高于一切",
		desc = "以美国阵营获胜",
		image = "nextoren/achievements/ahive111.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "nazi",
		achievements_name = "为元首进军",
		desc = "以第三帝国阵营获胜",
		image = "nextoren/achievements/ahive15.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "cannibal",
		achievements_name = "丰盛的晚餐",
		desc = "作为食人者吃掉10具尸体",
		image = "nextoren/achievements/ahive138.jpg",
		secret = false,
		countable = true,
		countnum = 10,
		giveatendround = false,
		awardexp = 100,
		textnotify = false
	},

	{
		name = "scp914",
		achievements_name = "命运之轮",
		desc = "在SCP-914中加工出O5卡",
		image = "nextoren/achievements/ahive43.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},
	{
		name = "scp914burger",
		achievements_name = "多么有趣的精品店",
		desc = "在SCP-914中把尸体加工成汉堡",
		image = "nextoren/achievements/ahive43.jpg",
		secret = true,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "radioactive",
		achievements_name = "那是86年……",
		desc = "喝下放射性DADO",
		image = "nextoren/achievements/ahive25.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "spawn_scp",
		achievements_name = "实验的牺牲品",
		desc = "成为SCP",
		image = "nextoren/achievements/ahive61.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "death",
		achievements_name = "I won’t be coming home",
		desc = "接受自己的死亡",
		image = "nextoren/achievements/ahive26.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "clocker",
		achievements_name = "菲舍尔会为我骄傲",
		desc = "成为ONP清除者",
		image = "nextoren/achievements/ahive72.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "backstab",
		achievements_name = "来自管道工的问候",
		desc = "用近战武器从背后袭击玩家",
		image = "nextoren/achievements/ahive69.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "mtfagent",
		achievements_name = "老大哥在看着你",
		desc = "作为UB特工追踪间谍",
		image = "nextoren/achievements/ahive128.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "runbitch",
		achievements_name = "快跑啊混蛋",
		desc = "在爆炸前5秒逃脱",
		image = "nextoren/achievements/ahive46.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "protocol",
		achievements_name = "Eisenskorpion协议",
		desc = "作为调度员或GOC召唤支援",
		image = "nextoren/achievements/ahive132.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "weaponry",
		achievements_name = "拿起武器",
		desc = "作为安保在办公区获得装备",
		image = "nextoren/achievements/ahive123.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "armor",
		achievements_name = "用不用得上，以后再说",
		desc = "作为科学家或D级戴上头盔和防弹衣",
		image = "nextoren/achievements/ahive88.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

	{
		name = "deffib",
		achievements_name = "不抛弃同伴",
		desc = "用除颤器复活玩家",
		image = "nextoren/achievements/ahive127.jpg",
		secret = false,
		countable = false,
		countnum = 0,
		giveatendround = false,
		awardexp = 100,
		textnotify = false,
	},

}